# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: All The Things
    before: |
      echo '' >> ~/.bashrc
      echo '# Install Ruby Gems to /workspace/gems' >> ~/.bashrc
      echo 'export GEM_HOME="/workspace/gems"' >> ~/.bashrc
      echo 'export PATH="/workspace/gems/bin:$PATH"' >> ~/.bashrc
    init: >
      source ~/.bashrc &&
      gem install bundler &&
      bundle install
    command: >
      source ~/.bashrc &&
      bundle exec jekyll serve --livereload

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-browser