tasks:
  - name: Update ~/.bashrc
    before: >
      echo '# Install Ruby Gems to /workspace/gems' >> ~/.bashrc
      echo 'export GEM_HOME="/workspace/gems"' >> ~/.bashrc
      echo 'export PATH="/workspace/gems/bin:$PATH"' >> ~/.bashrc
  - name: Install Bundler
    init: >
      gem install bundler &&
      bundle install &&
      gp sync-done bundle
  - name: Start Jekyll
    init: gp sync-await bundle
    command: bundle exec jekyll serve --livereload

ports:
  - port: 4000
    onOpen: open-browser
